FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# set path to our python api file
ENV MODULE_NAME="strawberry_subscription_auth.main"

# install poetry
RUN pip install poetry

# disable virtualenv for poetry
RUN poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

# install dependencies
RUN poetry install

EXPOSE 80:8000

COPY ./ /app

CMD ["uvicorn", "strawberry_subscription_auth.main:app", "--host", "0.0.0.0", "--port", "80"]
